#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

//// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');
// 单独定义 配置 目录
defined('CONF_PATH') or define('CONF_PATH',__DIR__ . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR );
// 加载框架引导文件
require __DIR__.'/thinkphp/console.php';
